print("Whats up")
print (5+5)
print(10/2)
name = input("Type your name?:")
print(name)
age = input("How old are you?:")
print(age)
color = input("what is your favorite color?:")
print(color)
print("Your name is Ej and you are 15 years old and your favorite color is blue")